import type { NextPage } from 'next';
import Head from 'next/head';
import { Flex, Heading } from '@chakra-ui/react';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex alignItems="center" p="2rem 1rem" flexDir="column">
        {/* {loading && <Loading text="loading..." />} */}
        <Heading
          as="h2"
          fontSize="2.25rem"
          mb={4}
          fontWeight={400}
          alignSelf="flex-start"
          color="green.500"
        >
          Explore Collections
        </Heading>
        {/* <CollectionList collectionList={collectionList} /> */}
      </Flex>
    </div>
  );
};

export default Home;
